// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi85tbXtY3QsmxUq32GIspuI4YPs7qPv8',
    appId: '1:264299772877:web:530f7912b1e999ad692284',
    messagingSenderId: '264299772877',
    projectId: 'blockpay-74134',
    authDomain: 'blockpay-74134.firebaseapp.com',
    storageBucket: 'blockpay-74134.appspot.com',
    measurementId: 'G-J4Q73V42FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0SqglzvqSzTtBnBUhazu-nfnbG-8foME',
    appId: '1:264299772877:android:3a94456aea774509692284',
    messagingSenderId: '264299772877',
    projectId: 'blockpay-74134',
    storageBucket: 'blockpay-74134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFrQWQMYql8rjtRdZjNjJHY_4NRD0Eb38',
    appId: '1:264299772877:ios:4de917a24edbe5a4692284',
    messagingSenderId: '264299772877',
    projectId: 'blockpay-74134',
    storageBucket: 'blockpay-74134.appspot.com',
    iosClientId: '264299772877-r26tembg8i7gmf48dne7r7crh828tt0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockpayFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFrQWQMYql8rjtRdZjNjJHY_4NRD0Eb38',
    appId: '1:264299772877:ios:4de917a24edbe5a4692284',
    messagingSenderId: '264299772877',
    projectId: 'blockpay-74134',
    storageBucket: 'blockpay-74134.appspot.com',
    iosClientId: '264299772877-r26tembg8i7gmf48dne7r7crh828tt0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockpayFrontend',
  );
}
